# we don't want to do any en-US, l10n, or parter based tasks for graph 2
platforms: {}
release_platforms: []
final_verify_platforms:
  - "linux"
  - "linux64"
  - "win32"
  - "win64"
  - "macosx64"
uptake_monitoring_platforms:
  - "linux"
  - "linux64"
  - "win32"
  - "win64"
  - "macosx64"
l10n_release_platforms: []
partner_repacks_platforms: []
eme_free_repacks_platforms: []
sha1_repacks_platforms: []

updates_builder_enabled: false
source_enabled: false
bouncer_enabled: false
signing_class: "release-signing"
signing_cert: "release"
root_home_dir: "desktop"
# funsize
updates_enabled: false
checksums_enabled: false
push_to_candidates_enabled: false
update_verify_enabled: false
push_to_releases_enabled: true
# rc graph 2 only needs final_verify_channels
channels:
publish_to_balrog_channels:
    - "release"
final_verify_channels:
    - "release"
postrelease_bouncer_aliases_enabled: true
uptake_monitoring_enabled: true
postrelease_version_bump_enabled: true
postrelease_mark_as_shipped_enabled: true

product: "firefox"
stage_product: "firefox"
funsize_product: "firefox"
repo_path: "releases/mozilla-release"
branch: "mozilla-release"
funsize_balrog_api_root: "http://balrog/api"
balrog_api_root: "https://aus4-admin.mozilla.org/api"
build_tools_repo_path: "build/tools"
tuxedo_server_url: "https://bounceradmin.mozilla.com/api"
push_to_releases_automatic: true
beetmover_candidates_bucket: "net-mozaws-prod-delivery-firefox"
snap_enabled: false
update_verify_channel: null
update_verify_requires_cdn_push: false
